//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30309.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wayloop.Highlight.Tests.Engines.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InputOutput {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InputOutput() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wayloop.Highlight.Tests.Engines.Resources.InputOutput", typeof(InputOutput).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public class A
        ///{
        ///    // Comment
        ///    public void Test()
        ///    {
        ///        string test = &quot;ABC&quot;;
        ///
        ///        return;
        ///    }
        ///}.
        /// </summary>
        internal static string CSharp_Sample1 {
            get {
                return ResourceManager.GetString("CSharp_Sample1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span style=&quot;color: Black;background-color: Transparent;font-family: Courier New;font-size: 11px;font-weight: normal;&quot;&gt;&lt;span style=&quot;color: Blue;background-color: Transparent;font-family: Courier New;font-size: 11px;font-weight: normal;&quot;&gt;public&lt;/span&gt; &lt;span style=&quot;color: Blue;background-color: Transparent;font-family: Courier New;font-size: 11px;font-weight: normal;&quot;&gt;class&lt;/span&gt; A
        ///{
        ///    &lt;span style=&quot;color: Green;background-color: Transparent;font-family: Courier New;font-size: 11px;font-weight: normal;&quot;&gt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSharp_Sample1_HtmlOutput {
            get {
                return ResourceManager.GetString("CSharp_Sample1_HtmlOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javascript&quot; src=&quot;http://example.org/file.js&quot;&gt;&lt;/script&gt;
        ///&lt;div id=&quot;test&quot;&gt;&lt;a href=&quot;#&quot; title=&quot;Link&quot;&gt;Link&lt;/a&gt;&lt;/div&gt;.
        /// </summary>
        internal static string Html_Sample1 {
            get {
                return ResourceManager.GetString("Html_Sample1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span style=&quot;color: Black;background-color: Transparent;font-family: Courier New;font-size: 11px;font-weight: normal;&quot;&gt;&lt;span style=&quot;color: Blue;background-color: Transparent;font-family: Courier New;font-size: 11px;font-weight: normal;&quot;&gt;&amp;lt;&lt;/span&gt;&lt;span style=&quot;color: Maroon;background-color: Transparent;font-family: Courier New;font-size: 11px;font-weight: normal;&quot;&gt;script&lt;/span&gt; &lt;span style=&quot;color: Red;background-color: Transparent;font-family: Courier New;font-size: 11px;font-weight: normal;&quot;&gt;type&lt;/span&gt;&lt;s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Html_Sample1_HtmlOutput {
            get {
                return ResourceManager.GetString("Html_Sample1_HtmlOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;input type=&quot;checkbox&quot; value=&quot;a&quot; checked disabled /&gt;.
        /// </summary>
        internal static string Html_Sample2 {
            get {
                return ResourceManager.GetString("Html_Sample2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span style=&quot;color: Black;background-color: Transparent;font-family: Courier New;font-size: 11px;font-weight: normal;&quot;&gt;&lt;span style=&quot;color: Blue;background-color: Transparent;font-family: Courier New;font-size: 11px;font-weight: normal;&quot;&gt;&amp;lt;&lt;/span&gt;&lt;span style=&quot;color: Maroon;background-color: Transparent;font-family: Courier New;font-size: 11px;font-weight: normal;&quot;&gt;input&lt;/span&gt; &lt;span style=&quot;color: Red;background-color: Transparent;font-family: Courier New;font-size: 11px;font-weight: normal;&quot;&gt;type&lt;/span&gt;&lt;sp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Html_Sample2_HtmlOutput {
            get {
                return ResourceManager.GetString("Html_Sample2_HtmlOutput", resourceCulture);
            }
        }
    }
}
